id = "npm-package-json-checker"
name = "NPM Package.json Update Checker"
version = "1.0.4"
schema_version = 1
authors = ["Evan Simpson <evan@evan.news>"]
description =  "ðŸ“¥ Highlights outdated npm packages and shows changelogs in package.json. Changelogs from GitHub releases and/or CHANGELOG.md. Shown minimalistically without UI bloat."
repository = "https://github.com/e-simpson/zed-npm-update-checker"

[language_servers.npm-package-json-checker-lsp]
name = "NPM Package.json Update Checker LSP"
languages = ["JSON"]
