id = "zed-npm-update-checker"
name = "NPM Package.json Update Checker"
version = "1.0.0"
schema_version = 1
authors = ["Evan Simpson <evan@evan.news>"]
description = "Highlights outdated npm packages in package.json files."
repository = "https://github.com/e-simpson/zed-npm-update-checker"

[language_servers.npm-update-checker-lsp]
name = "NPM Update Checker LSP"
languages = ["JSON"]
